### ISSUE TITLE
Only the main web page is displayed correctly

### ISSUE THREAD

**Issue by mpailloncy** [ToulouseJug/toulousejug.github.io#12]
All pages except the main web page are not displayed correctly => Paths to static resources (css/js/images) are incorrect (http://www.toulousejug.org/2017/09/11/css/bootstrap.min.css instead of http://www.toulousejug.org/css/bootstrap.min.css for example).

Seems related to a bad interpretation of "{{ site.baseurl }}" variable inside `_layout/default.html` template.

**Comment by lcapdecomme** [comment]
salut,
En attendant mieux, j'ai utilisé ton commit pour régler ce problème de chargements des ressources statiques.
Je ne vois pas bien pourquoi cette variable n'est plus correctement interprété . 
Lionel

**Comment by mpailloncy** [comment]
Okay cool. Finalement pas pris le temps de le faire hier soir, merki Lionel :-)
