### ISSUE TITLE
No post in web site ; 'nil' layout in feed page

### ISSUE THREAD

**Issue by nicolas-zozol** [ToulouseJug/toulousejug.github.io#6]
I have in the `feed/index.html`file  :

```

---
layout: nil

---
```

in the console, I have then : `Build Warning: Layout 'nil' requested in feed/index.html does not exist.` Then there are no post displayed in the page.

I previously had to change config file because of a deprecation warning on pagination:

```
paginate: 5
encoding: UTF-8
gems: [jekyll-paginate]   #<<< added that

```

Any clue ?

![capture d ecran 2016-10-24 a 19 31 40](https://cloud.githubusercontent.com/assets/912634/19656502/8c84f42a-9a20-11e6-8720-631bfe18bf94.png)

**Comment by lcapdecomme** [comment]
Bonjour,
D'après ce post  (https://github.com/jekyll/jekyll-help/issues/112), il ne faut plus utiliser nil mais null. Cela a été ok pour moi. 
Concernant les posts qui ne s'affichent plus, j'ai du remplacer le tag paginator par sites. Pas trop creuser pour savoir pourquoi ... Peut-être ma version 3 de jekyll ?
